include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

# https://dart.dev/tools/linter-rules#[name]
linter:
  rules:
    # unawaited_futures: false
    # control_flow_in_finally: false
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    use_is_even_rather_than_modulo: false
    prefer_asserts_with_message: false
    # avoid_final_parameters: false
    directives_ordering: false
    use_super_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    require_trailing_commas: true
    always_declare_return_types: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    # discarded_futures: true
    # prefer_final_parameters: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
