name: protoo_client
version: 0.3.3
description: Dart version of the protoo-client library.
homepage: https://github.com/cloudwebrtc/dart-protoo-client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  events2: ^1.0.0
  logging: ^1.2.0
  retry: ^3.1.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1
